### PR TITLE
mc data model: updated particle model for better efficiency on disk

### PR DESCRIPTION
**Pull request by decibelcooper**
This is thanks to work by Sergei Chekanov (@chekanov).

### CODE REVIEW

**Comment by decibelcooper** [comment]
Hi Sergei (@chekanov),

If you can, please check that this change works for your four Pythia8 test cases.  Note that there are a couple minor changes (naming of mother -> parent, daughter -> child), and a couple of changes that break wire compatibility with what you've generated already.  I chose uint64 values for time and energy rather than sint64.

**Comment by chekanov** [comment]
Hi, David

 Thanks. It looks good. But I've noticed that when I use "VarintPackedParticles", it gives somewhat larger file size (119 MB) compared to 105 MB  (when I use ProMC) for 20,000 pp events. Is it possible that extra unused messages in this data model require more space?

Sergei

**Comment by decibelcooper** [comment]
Hi Sergei,

I don't think so, but there is a problem that I have now fixed.  I had missed changing over a couple fields in VarintPackedParticles from float to int.  Can you please check (hopefully) once more?

**Comment by chekanov** [comment]
Hi, David

 Now it looks good. I'm getting exactly 106 MB as for ProMC. Is it possible for you to add comments in this mc.proto file (before each message statement) that explain why do we keep such messages in this file.

I guess we have finished with mc.proto

best, Sergei

**Comment by decibelcooper** [comment]
Hi Sergei,

Thank you!  Comments added.  I will now merge this PR.

**Pull request merged**
