### PR TITLE
Changed the mc.proto model

### PR DESCRIPTION
**Pull request by chuwyjr**

### CODE REVIEW

**Comment by decibelcooper** [comment]
Hi @chuwyjr, I will need you to rebase with my master branch and also add the mc.proto and go+java generated files.

**Comment by decibelcooper** [comment]
Thanks!  I suggest that before merging we add comments and remove the unnecessary whitespace here: https://github.com/chuwyjr/proio/blob/314b6983e2dfbd20ff52b2baece17d27bb68638a/model/mc.proto#L19-L32

Also, what is the reason for not having keys for these repeated values here: https://github.com/chuwyjr/proio/blob/314b6983e2dfbd20ff52b2baece17d27bb68638a/model/mc.proto#L9-L15

**Comment by decibelcooper** [comment]
Hi @chuwyjr, I suggest changing fields at https://github.com/chuwyjr/proio/blob/83210c4be34a2f7998cfe8625150de35cb7f959e/model/mc.proto#L21 and https://github.com/chuwyjr/proio/blob/83210c4be34a2f7998cfe8625150de35cb7f959e/model/mc.proto#L26 to be `repeated`, and removing the `iarray` and `darray` fields of MCParameters.  This I think would be a more compact model without (IMO) being overly cumbersome.  Thoughts?

**Comment by chuwyjr** [comment]
Hello @decibelcooper, i agree having  https://github.com/chuwyjr/proio/blob/83210c4be34a2f7998cfe8625150de35cb7f959e/model/mc.proto#L21 and  https://github.com/chuwyjr/proio/blob/83210c4be34a2f7998cfe8625150de35cb7f959e/model/mc.proto#L26 be repeated would be better than having them be required. I also think that removing iarray and darray would be better since MapInt and MapDouble can store their information.

**Comment by decibelcooper** [comment]
@chuwyjr excellent!  We still need to get the generated code up to date, and then squash the commits (rebase interactively and `fixup` the commits into one commit with a descriptive message).  Please make sure to update the generated code (only the mc data model files this time) before squashing.

**Pull request merged**
